name: 'Node Yarn Chromium Aciton'
description: 'Node, Yarn, and Chromium in a GitHub Action'
inputs:
  cmd:
    description: 'Run commands inside container'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.cmd }}