name: Docker build and push
on:
    push:
        branches: [main]
        paths-ignore:
            - ".github/**"
    workflow_dispatch:

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.PERSONAL_TOKEN }}

            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v3
              with:
                  images: |
                      ghcr.io/alvarlagerlof/action-node-yarn-chromium
                  tags: |
                      type=sha
            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  context: .
                  push: ${{ github.event_name != 'pull_request' }}
                  tags: |
                      ghcr.io/alvarlagerlof/action-node-yarn-chromium:latest
                      ${{ steps.meta.outputs.tags }}